target("clay_gfx")
    set_kind("static")
    add_files("src/**.cpp")
    add_includedirs("include/", {public = true})
    add_packages("vulkansdk", "libsdl")
    add_deps("proxy", "clay_core")
    set_toolchains("clang-cl")
target_end()